title: Huynh Phu Xuan
description: Behavioral Economist | Market Research | Social Analyst
baseurl: ""
url: "https://xuanhvl-learning.github.io"

markdown: kramdown
permalink: /blog/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
